version: '3'

networks:
  backend:

services:

  unicorn:
    build:
      dockerfile: cpu.dockerfile
      context: .
    environment:
      - IMAGE_LIMIT=100000
    networks:
      - backend
    volumes:
      - .:/app
