version: '3'

networks:
  backend:

services:

  unicorn:
    build: 
      dockerfile: cpu.dockerfile
      context: .
    environment:
      - IMAGE_LIMIT=4000
    networks:
      - backend
    volumes:
      - .:/app

