name: cluster            
channels:
- defaults
- conda-forge
- georgedimitriadis
dependencies:
# - anaconda-client
- spikesorting_tsne
- fastcluster
- hdbscan
- python=3.6
- Pillow
- requests
- pytest
- numpy
- cython
- scikit-learn
- Keras
- pip:                
  - cachetools