name: base
channels:
- defaults
- conda-forge
- georgedimitriadis
dependencies:
- anaconda-client
- spikesorting_tsne
- hdbscan
- python=3.6
- requests
- pytest
- numpy
- scikit-learn
- pip:
  - cachetools
